import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/utils/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div  className="px-4 md:px-0 ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
